### ISSUE TITLE
RFC0019 Does not follow the new template

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin-rfcs#75]
As titled RFC0019 https://github.com/mimblewimble/grin-rfcs/blob/master/text/0019-deprecate-http-tx.md does not follow the new template. Ping @j01tz,

**Comment by j01tz** [comment]
Thanks, I must have initially created it before the template changed (and didn't realize it had changed). I'll open a PR with the changes tomorrow :+1:
